base_images_url: /images/badges
types:
  1: 
    name: Founder
    image: founder.png
    description: Founder of jamMm.in
    
  2: 
    name: Alpha Musician
    image: alphamusician.png
    description: A chosen set of musicians that were involved in the early development of jamMm.in. These musicians helped define jamMm.in and were present from the Pre-Alpha release.

  3: 
    name: Alpha Rhythm Session
    image: alpharhythmsession.png
    description: The set of musicians that took part in the "Alpha Rhythm Session".
  4:
    name: Core Team
    image: coreteam.png
    description: jamMm.in Core Team Member