account:
    left_panel: menu
    
    home:
        middle_panel: home
        right_panel: right
        
    songs:
        middle_panel: songs
        
    jams:
        middle_panel: jams
        
profile:
    left_panel: menu
    middle_panel: profilehome
    right_panel: right

    songs:
        middle_panel: songs
        right_panel: nil
    
    jams: 
        middle_panel: jams
        right_panel: nil
        
    info:
        middle_panel: info

    usernotfound:
        middle_panel: usernotfound    
        left_panel: nil
        right_panel: nil

signup:
    middle_panel: form