
account:
    left_panel: menu
    right_panel: in_progress_music
    
    home:
        middle_panel: home
        
    songs:
        middle_panel: songs
        
    jams:
        middle_panel: jams
        
profile:
    