account:
    left_panel: menu
    right_panel: in_progress_music
    
    home:
        middle_panel: home
        
    songs:
        middle_panel: songs
        
    jams:
        middle_panel: jams
        
profile:
    left_panel: menu
    middle_panel: profilehome
    right_panel: nil

    songs:
        middle_panel: songs
    
    jams: 
        middle_panel: jams
        
    info:
        middle_panel: info

    usernotfound:
        middle_panel: usernotfound    
        left_panel: nil
        right_panel: nil

signup:
    middle_panel: form
    
    
    
