
account:
    left_panel: menu
    right_panel: in_progress_music
    
    home:
        middle_panel: home
        
    songs:
        middle_panel: songs
        
    jams:
        middle_panel: jams
        
profile:
    left_panel: menu
    middle_panel: profilehome

    songs:
        middle_panel: songs
    
    jams: 
        middle_panel: jams
    
signup:
    middle_panel: form
    
    
    
