---
  environment: production
  chdir: /home/jammmin/webserver/app
  address: 127.0.0.1
  user: root
  group: root
  port: 4567
  pid: /home/jammmin/processes/thin
  rackup: /home/jammmin/webserver/app/config/thin.ru
  log: /home/jammmin/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
